### ISSUE TITLE
Whether generated event+place are used

### ISSUE THREAD

**Issue by jayleicn** [jamespark3922/visual-comet#5]
Hi @jamespark3922, 

Do you use generated `event+place` for the circled rows in Table 2? Based on my understanding, for these rows, event+place are used only at the training phase, but not at test time, either ground-truth or generated. Could you confirm this?
![image](https://user-images.githubusercontent.com/15768405/105931275-e311ac80-6018-11eb-9f50-d816891b6665.png)

Meanwhile, `[Image + Event + Place + PG + EP Loss]` with `Text Given: Yes` and `[Image + Event + Place + PG + EP Loss]` with `Text Given: No` are the same trained model, and only differ at whether the ground-truth `event+place` is given at test time, is this correct?

Lastly, do you have language metric (BLEU-2, etc.) results for the `With Generated Text Input` experiments in Table 7?
![image](https://user-images.githubusercontent.com/15768405/105932526-fb82c680-601a-11eb-8874-846d5b5d3c17.png)

Best,
Jie

**Comment by jamespark3922** [comment]
Hi Jie,

1. What you described is correct. I did not use generated event + place text for these rows, because doing so seemed to hurt the performance, including the language metric. 

2. Correct, the `[Image + Event + Place + PG + EP Loss]` model is trained the same but the test setup was different. 

3. Unfortunately, I do not have the exact numbers, but they were lower than the results for "Text without input".

Of course, there's always room for improvement to incorporate generated event + place, and it'll be a fair comparison/improvement to results without GT text input.

**Comment by jayleicn** [comment]
Thank you James for the clarification! This is very helpful!
